### ISSUE TITLE
데이터 분석의 떨어지는 객관성

### ISSUE THREAD

**Issue by Jungjaehee** [WBPBP/preshoes-model#3]
현재 직면하고 있는 문제는 다음과 같습니다.
1. 데이터 수집 시에 걸을 수 있는 횟수가 한정되어 있어 각 걸음걸이 판단의 기준이 될 데이터를 제대로 마련하지 못합니다.
2. 데이터를 수집할 때 참여하는 실험자와 테스터가 같아 정확한 걸음걸이 분류가 제대로 이루어지는 객관적으로 확인이 불가하여 성능 측정에 어려움이 보입니다.

**Comment by potados99** [comment]
공유 감사합니다.

**Comment by hseol** [comment]
2번에 대해서 , 그래서 좀더 테스터가 수집을 할때는 극단적인 걸음걸이 양상을 보여줄 수 있게 하는 것이 목표였는데.. 지켜지지 않은 것 같습니다.

**Comment by potados99** [comment]
ㅠㅠ..
